// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6nad687sxOjQcVv4W0xgPQj32SrMNqEk',
    appId: '1:819841175509:web:97dce299cd7710c73f775c',
    messagingSenderId: '819841175509',
    projectId: 'creativa-app-a86a6',
    authDomain: 'creativa-app-a86a6.firebaseapp.com',
    storageBucket: 'creativa-app-a86a6.firebasestorage.app',
    measurementId: 'G-C8D6DBGNF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuJU336hHHnfseMykCpkFRNfBYOHskTJY',
    appId: '1:819841175509:android:a00c3988ec0e46a03f775c',
    messagingSenderId: '819841175509',
    projectId: 'creativa-app-a86a6',
    storageBucket: 'creativa-app-a86a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJH8OPb1nPovDGPcsmrAK-f9y4xbmtpE',
    appId: '1:819841175509:ios:918c78db28d7c46d3f775c',
    messagingSenderId: '819841175509',
    projectId: 'creativa-app-a86a6',
    storageBucket: 'creativa-app-a86a6.firebasestorage.app',
    iosBundleId: 'com.example.creativaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJH8OPb1nPovDGPcsmrAK-f9y4xbmtpE',
    appId: '1:819841175509:ios:918c78db28d7c46d3f775c',
    messagingSenderId: '819841175509',
    projectId: 'creativa-app-a86a6',
    storageBucket: 'creativa-app-a86a6.firebasestorage.app',
    iosBundleId: 'com.example.creativaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6nad687sxOjQcVv4W0xgPQj32SrMNqEk',
    appId: '1:819841175509:web:66903258c1a0b88b3f775c',
    messagingSenderId: '819841175509',
    projectId: 'creativa-app-a86a6',
    authDomain: 'creativa-app-a86a6.firebaseapp.com',
    storageBucket: 'creativa-app-a86a6.firebasestorage.app',
    measurementId: 'G-YVN79Y710M',
  );
}
